type: pyaml.accelerator
facility: pyAML test facility
machine: pyaml test machine
data_folder: null
energy: null
simulators:
- type: pyaml.lattice.simulator
  lattice: ${env:PYAML_TEST_LATTICE}
  name: design
devices:
- type: pyaml.magnet.quadrupole
  name: QF_001
  model:
    type: pyaml.magnet.identity_model
    physics: ''
